package com.hatexml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-05T15:42:35.109+01:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "myEndpointService",
                  wsdlLocation = "file:/C:/Users/a761155/Documents/workspace-intelij/hatexml/src/main/resources/wsdl/myWsdl.wsdl",
                  targetNamespace = "http://hatexml.com")
public class MyEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hatexml.com", "myEndpointService");
    public final static QName MyEndpoint = new QName("http://hatexml.com", "myEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/a761155/Documents/workspace-intelij/hatexml/src/main/resources/wsdl/myWsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyEndpointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/a761155/Documents/workspace-intelij/hatexml/src/main/resources/wsdl/myWsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MyEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MyEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MyEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MyEndpoint
     */
    @WebEndpoint(name = "myEndpoint")
    public MyEndpoint getMyEndpoint() {
        return super.getPort(MyEndpoint, MyEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyEndpoint
     */
    @WebEndpoint(name = "myEndpoint")
    public MyEndpoint getMyEndpoint(WebServiceFeature... features) {
        return super.getPort(MyEndpoint, MyEndpoint.class, features);
    }

}
